# .streamlit/secrets.toml

# Pilih salah satu API provider:

# Untuk Groq API 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
GROQ_API_KEY = "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"

# ATAU untuk DeepSeek API  
DEEPSEEK_API_KEY = "sk-bfa3198c0c0e4c03812b804e5a5dafb7"

# ATAU untuk OpenAI API (jika pakai GPT)
OPENAI_API_KEY = "your-openai-api-key-here"

#huggingface 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
# Untuk Hugging Face (wajib untuk model premium)
HF_API_KEY = "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"